services:
  mongo:
    image: mongo
    ports:
      - '127.0.0.1:27017:27017'
  myapp:
    build: .
    environment:
      WAIT_HOSTS: mongo:27017
      DOCKER_DB: true
    ports:
      - '5000:5000'
